### PR TITLE
make linking transactions to keys case-insensitive

### LINKED ISSUE #4148: Forbes paywall bug reproduction steps
To reproduce the Forbes paywall bug, follow these steps:

1. start locksmith `cd locksmith && npm run dev`
2. Change the 2nd lock in the configuration for `paywall/src/static/adremover/prod.html` to `0x7ee1b5CBd032A6258171580484Ac3aDc63Ee130A`
3. start the paywall in production mode `cd paywall && UNLOCK_ENV=prod DEBUG=1 npm run dev`

For step 2, your config should look like this:

```js
    <script>
      var unlockProtocolConfig = {
        locks: {
          '0x2BDb87333b15E20d948BC5235569f0cA3E6c707C': {
            name: 'One Day',
          },
          '0x7ee1b5CBd032A6258171580484Ac3aDc63Ee130A': {
            name: 'A Good Deal!',
          },
        },
        icon:
          'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAwIDI1NiI+CiAgPHBhdGggZD0iTTQ0OS45Mzk4OCwyMzAuMDUzNzFoNTMuMDRWMGgtNTMuMDRaTTIxNS4xMDIsMTUuOTc2MDdIMTU5LjUwNThWNzEuNTgzODZINzAuNjc5NjNWMTUuOTc2MDdIMTUuMDgzVjcxLjU4Mzg2SDBWOTguMDA0MTVIMTUuMDgzdjQxLjYyNTczYzAsNTIuMDgxNTUsNDUuMDUyMjQsOTQuNTc3NjQsMTAwLjMyOTEsOTQuNTc3NjQsNTQuOTU3LDAsOTkuNjg5OTQtNDIuNDk2MDksOTkuNjg5OTQtOTQuNTc3NjRWOTguMDA0MTVoMTQuOTY0VjcxLjU4Mzg2SDIxNS4xMDJaTTE1OS41MDU4LDEzOS42Mjk4OGMwLDI0LjYwMy0xOS40OTA3Miw0NC43MzI0Mi00NC4wOTM3NSw0NC43MzI0MmE0NC44NjM2Nyw0NC44NjM2NywwLDAsMS00NC43MzI0Mi00NC43MzI0MlY5OC4wMDQxNUgxNTkuNTA1OFpNMzQ4LjY1NjY4LDY3LjA5OTEyYy0xOS4xNzEzOSwwLTM3LjcwMzYyLDguNjI3LTQ4LjI0NzU2LDI0LjI4MzJIMjk5Ljc3bC0zLjE5NDgzLTE5LjgxMDA1aC00Ni42NDk5VjIzMC4wNTM3MWg1My4wNHYtODIuNDM2YzAtMTguMjEyNDEsMTQuMDU5MDgtMzIuOTEwMTYsMzAuOTkzNjUtMzIuOTEwMTYsMTcuNTczMjUsMCwzMS4zMTI1LDE0LjY5Nzc1LDMxLjMxMjUsMzIuMjcxNDh2ODMuMDc0NzFoNTMuMDR2LTg4LjE4N0M0MTguMzExNDYsOTkuNjg5OTQsMzkxLjQ3MjExLDY3LjA5OTEyLDM0OC42NTY2OCw2Ny4wOTkxMlptNjgwLjg3Njk1LDc3LjMyMzI0LDY1LjE4MTY0LTcyLjg1MDA5aC02NS41MDFsLTUxLjEyMyw1OS40MzA2NmgtLjk1OVYwaC01My4wNFYyMzAuMDUzNzFoNTMuMDRWMTU3Ljg0MjI5aC45NTlsNTIuNzIwNyw3Mi4yMTE0Mmg2Ni43NzkzWk02MTMuMjA4NDQsNjcuMDk5MTJjLTQ5LjUyNTQsMC05MC40MjM4MywzNy43MDMxMy05MC40MjM4Myw4My43MTM4N3M0MC44OTg0Myw4My4zOTQ1Myw5MC40MjM4Myw4My4zOTQ1Myw5MC40MjM4Mi0zNy4zODM3OSw5MC40MjM4Mi04My4zOTQ1M1M2NjIuNzMzODMsNjcuMDk5MTIsNjEzLjIwODQ0LDY3LjA5OTEyWm0wLDEyMC43NzgzMmMtMjAuMTI5ODksMC0zNy4wNjQ0Ni0xNi45MzQ1Ny0zNy4wNjQ0Ni0zNy4wNjQ0NXMxNi45MzQ1Ny0zNy4wNjQ0NSwzNy4wNjQ0Ni0zNy4wNjQ0NSwzNy4zODM3OCwxNi45MzQ1NywzNy4zODM3OCwzNy4wNjQ0NVM2MzMuMzM4MzIsMTg3Ljg3NzQ0LDYxMy4yMDg0NCwxODcuODc3NDRaTTgxNC44MTg3OSwxMTMuNDI5MmMxNS42NTYyNSwwLDI4LjQzNzUsOC45NDY3OCwzMy4yMzA0NywyMS40MDc3MWg1My45OThjLTUuNDMxNjQtMzcuMDY0LTQxLjUzNzExLTY3LjczNzc5LTg2LjI2OTUzLTY3LjczNzc5LTQ5Ljg0NTcsMC05MS4wNjM1LDM3LjcwMzEzLTkxLjA2MzUsODMuNzEzODdzNDEuMjE3OCw4My4zOTQ1Myw5MS4wNjM1LDgzLjM5NDUzYzQzLjc3MzQ0LDAsODEuMTU3MjMtMjkuMzk2LDg2LjI2OTUzLTY4LjA1NzYyaC01My45OThjLTUuNzUyLDEzLjEwMDEtMTcuNTc0MjIsMjEuNDA3NzItMzMuMjMwNDcsMjEuNDA3NzJBMzYuOTU1MSwzNi45NTUxLDAsMCwxLDc3OC4wNzQ2NSwxNTAuODEzQzc3OC4wNzQ2NSwxMzAuNjgzMTEsNzk0LjM2OTU3LDExMy40MjkyLDgxNC44MTg3OSwxMTMuNDI5MloiLz4KPC9zdmc+Cg==',
        callToAction: {
          default:
            'Enjoy Lorem Ipsum without any ads for free or a little bit. Pay with Ethereum in just two clicks.',
        },
      }
    </script>
```

Then, navigate to:

`http://localhost:3001/static/adremover/prod.html`

and purchase a key on the 2nd lock.

### PR DESCRIPTION
**Pull request by cellog**
# Description

Case sensitivity existed across the paywall.

- lock addresses in the configuration
- lock address indices for keys
- lock address indices for locks

Because the end user controls the configuration, and can choose to manually type in lock addresses with all lower-cased values, it is necessary to do 2 things:

- lower-case all of the lock addresses from the configuration
- lower-case all uses of lock addresses as indices

With these 2 changes, cross-referencing keys, transactions and locks happens, regardless of how the lock address is placed in the configuration. This is a lot of files, but not a lot of logic changed.

# Issues

Fixes #4148 

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/components/checkout/Checkout.tsx [hunk 1]
```diff
@@ -36,15 +37,16 @@ export const Checkout = ({
         <p>{config.callToAction.default}</p>
       </Header>
       <CheckoutLocks>
-        {Object.values(locks).map(lock => {
+        {lockAddresses.map(lockAddress => {
+          const lock = locks[lockAddress]
```
Comment (cellog) [inline paywall/src/components/checkout/Checkout.tsx]: the key is lower-cased. The lock address is checksummed, and so case sensitive. This change ensures we map locks to their configuration names

File: paywall/src/data-iframe/blockchainHandler/keyStatus.js [hunk 2]
```diff
@@ -49,14 +49,21 @@ export function linkTransactionsToKey({
...
-  const account = key.owner
+  const account = key && key.owner ? key.owner.toLowerCase() : null
+  const lock = key && key.lock ? key.lock.toLowerCase() : null
   const keyPurchaseTransactions = Object.values(transactions)
     .filter(transaction => {
       // in theory, all transactions have already been filtered this way
       // but this is a sanity check to ensure we only process
       // key purchase transactions where the key was purchased
       // for the current account holder
-      return transaction.for === account && transaction.to === key.lock
```
Comment (cellog) [inline paywall/src/data-iframe/blockchainHandler/keyStatus.js]: we use `transaction.lock` instead of `transaction.to` because in live testing, there were transactions that lacked a `to` field, but all key purchase transactions have a `lock` field

File: paywall/src/unlock.js/setupPostOffices.ts [hunk 3]
```diff
@@ -14,6 +14,29 @@ interface process {
 
 declare const process: process
 
+export function normalizeConfig(unlockConfig: any) {
+  if (
```
Comment (cellog) [inline paywall/src/unlock.js/setupPostOffices.ts]: this is just filtering out configurations that would crash the lower-casing logic

File: paywall/src/unlock.js/setupPostOffices.ts [hunk 4]
```diff
@@ -14,6 +14,29 @@ interface process {
...
+    !unlockConfig ||
+    !unlockConfig.locks ||
+    typeof unlockConfig.locks !== 'object'
+  )
+    return unlockConfig
+  const lockAddresses = Object.keys(unlockConfig.locks)
+  if (!lockAddresses.length) {
+    return unlockConfig
+  }
+  const normalizedConfig = {
```
Comment (cellog) [inline paywall/src/unlock.js/setupPostOffices.ts]: this lower-cases all of the lock addresses as keys. This way configuration locks are always normalized to lowercase

File: paywall/src/data-iframe/blockchainHandler/locksmithTransactions.js [hunk 5]
```diff
@@ -20,16 +20,18 @@ export async function storeTransaction({
...
   const network = getNetwork()
+  // we use the transaction lock as the recipient
+  const recipient = transaction.lock
 
   const url = `${locksmithHost}/transaction`
 
   const payload = {
     transactionHash: transaction.hash,
-    sender: account.toLowerCase(),
+    sender: account,
```
Comment (cellog) [inline paywall/src/data-iframe/blockchainHandler/locksmithTransactions.js]: this is the one place it is unnecessary. locksmith converts all addresses to their checksummed addresses anyways (which is the other, better way to normalize ethereum addresses, but it requires ethers)

File: paywall/src/data-iframe/blockchainHandler/linkKeysToLocks.js [hunk 6]
```diff
@@ -13,10 +13,10 @@ export default async function linkKeysToLocks({
   return lockArray.reduce(
     (allLocks, lock) => ({
       ...allLocks,
-      [lock.address]: {
+      [lock.address ? lock.address.toLowerCase() : lock.address]: {
```
Comment (cnasc) [inline paywall/src/data-iframe/blockchainHandler/linkKeysToLocks.js]: Would it be a bit more readable to hoist these ternaries to the beginning of the function and declare the address as a variable? Not a blocker, I'll leave it up to you.

Comment (cellog) [reply paywall/src/data-iframe/blockchainHandler/linkKeysToLocks.js]: yeah I think so, it's awfully verbose as-is

File: paywall/src/components/checkout/Checkout.tsx (hunk 1 above)
Comment (cnasc) [reply paywall/src/components/checkout/Checkout.tsx]: Do you think you could add your github comment into the code here? Just because this one is not so obvious and I could see someone coming back and "improving" this code in the future and inadvertently introducing a bug.
