### PR TITLE
fix(networks): fix Uniswap Router for BNB in networks package

### LINKED ISSUE #12554: Swap and Purchase does not work on BNB chain
It looks like swap and purchase does not work on the BNB Chain.
This has been raised by one of our users with this checkout URL: https://nft.cryptoisfire.ai/
I chose the "Flame" membership and, even though I have enough BNB to swap to USDC, the transaction reverts.

I have [performed a simulation using Tenderly](https://dashboard.tenderly.co/julien51/unlock-protocol/simulator/new?stateOverrides=%5B%5D&rawFunctionInput=0x5e8f45020000000000000000000000005fb4c4b333fd8b713a42a6655e2ae83ec5f18897000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff1722376f9c3e0000000000000000000000004648a43b2c14da09fdf82b161150d3f634f4049100000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000002e424856bc30000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000030b010c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000001000000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c844000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b8ac76a51cc950d9822d68b83fe1ad97b32cd580d000bb8bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c84400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002643381899700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c0103534000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000041fe4abbdd5cc77b3fdfead4070e6087844269325f61eb41b3372aca76de72eed80631058c1c2303261bbfad63df4bce904a42733196e29f5a55d00b3104be6e8f1c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&simulationId=4e81c00f-645b-426e-8983-c721a40cc07f&value=0&contractAddress=0x5ad19758103d474bdf5e8764d97cb02b83c3c844&contractFunction=0x5e8f4502&functionInputs=0x5fb4c4b333fd8b713a42a6655e2ae83ec5f18897&functionInputs=0x0000000000000000000000000000000000000000&functionInputs=71801554787605566&functionInputs=0x4648a43b2c14da09fdf82b161150d3f634f40491&functionInputs=0x24856bc30000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000030b010c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000001000000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c844000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b8ac76a51cc950d9822d68b83fe1ad97b32cd580d000bb8bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c8440000000000000000000000000000000000000000000000000000000000000000&functionInputs=0x3381899700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c0103534000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000041fe4abbdd5cc77b3fdfead4070e6087844269325f61eb41b3372aca76de72eed80631058c1c2303261bbfad63df4bce904a42733196e29f5a55d00b3104be6e8f1c00000000000000000000000000000000000000000000000000000000000000&network=56&headerBlockNumber=30866463&headerTimestamp=1692078863) to confirm and indeed, we get a revert with `Error Message: InsufficientETH[]`.

When looking deeper in the transaction trace, it looks like the issue is coming from a malformed `swapCalldata` object.

### PR DESCRIPTION
**Pull request by clemsos**
# Description

# Issues

Fixes #12554
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

**Review by julien51 — APPROVED** [review]

File: packages/hardhat-helpers/src/uniswap.js [hunk 1]
```diff
@@ -113,67 +113,6 @@ const getUniswapTokens = async (chainId = 1) => {
   }
 }
 
-const routerAddresses = {
```
Comment (julien51) [inline packages/hardhat-helpers/src/uniswap.js:116]: thx!

**Review by julien51 — APPROVED** [review]
