### PR TITLE
feat(unlock-protocol-com): Fixed upcoming events 

### LINKED ISSUE #13527: Page served by events link in footers across site (multiple places) not working
The https://unlock-protocol.com/upcoming-events page is stale and not showing current events.

Screenshot 2024-03-26 at 4 46 02 PM

As a near-term fix, could redirect
https://unlock-protocol.com/upcoming-events
to
https://calendar.google.com/calendar/embed?src=c_dm3gud9ph6jqk7epq6jtij8u00%40group.calendar.google.com

Else, could invest time to fix page.

### PR DESCRIPTION
**Pull request by SVell**
# Description

Fixed current events, added year to start date and events are now sorted by date

# Issues

Fixes #13527
Refs #13527

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: unlock-protocol-com/src/pages/upcoming-events.tsx [hunk 1]
```diff
@@ -29,8 +29,8 @@ export const getStaticProps: GetStaticProps<UpcomingEventsProps> = async () => {
 
   return {
     props: {
-      upcomingEvents: upcomingEvents.reverse(),
-      pastEvents,
+      upcomingEvents,
+      pastEvents: pastEvents.reverse(),
```
Comment (julien51) [inline unlock-protocol-com/src/pages/upcoming-events.tsx:33]: Was that the issue?

**Review by julien51 — APPROVED** [review]
ok LG, can you please post a screenshot to make sure we have it fixed?

**Review by julien51 — APPROVED** [review]
