### PR TITLE
Fix locksmith image

### LINKED ISSUE #7515: Broken deployments
As part of the move to a [simpler staged docker](https://github.com/unlock-protocol/unlock/pull/7505) setup we might have broken deployments for locksmith.

Indeed, this new PR removes the `unlock-core` image that we used until now, as well as the customer image for locksmith which is actually used to deploy to Beanstalk.

We should restore this :) as well as cleanup the script to promote images (as well as data on docker.com)

### PR DESCRIPTION
**Pull request by clemsos**
# Description

updated Docker build to use multistage. Fix #7515

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: scripts/promote-image.sh [hunk 1]
```diff
@@ -4,20 +4,11 @@ set -e
...
-DOCKER_COMPOSE_FILE=$REPO_ROOT/docker/docker-compose.ci.yml
-COMMAND="yarn run ci"
 
-
-# Setting the right env var
-export UNLOCK_ENV=test
-
-# Build the core
-docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t unlock-core -f docker/unlock-core.dockerfile --cache-from unlockprotocol/unlock-core:$CIRCLE_BRANCH .
+echo $SERVICE
```
Comment (julien51) [inline scripts/promote-image.sh:8]: Leftover?

**Review by julien51 — APPROVED** [review]

File: scripts/promote-image.sh (hunk 1 above)
Comment (julien51) [inline scripts/promote-image.sh:8]:
```suggestion
```
