### PR TITLE
fix Telegram button display

### LINKED ISSUE #877: Something is wrong with our telegram button
When hovering in the top bar the telegram button does not behave like the other ones. I suspect is it placed too gar on the right as well.

telegram

### PR DESCRIPTION
**Pull request by cellog**
# Description

Fixes #877 by putting the Right spacer below normal content

out

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

**Comment by benwerd** [comment]
Just checking - have you checked on mobile?

File: unlock-app/src/components/interface/Header.js [hunk 1]
```diff
@@ -38,26 +46,20 @@ export default class Header extends React.PureComponent {
...
-              <Buttons.About size="48px" onClick={this.toggleMenu} />
-              <Buttons.Jobs size="48px" onClick={this.toggleMenu} />
-              <Buttons.Github size="48px" onClick={this.toggleMenu} />
-              <Buttons.Telegram size="48px" onClick={this.toggleMenu} />
-            </>
-          ) : (
-            ''
-          )}
+          {menu
+            ? navigationButtons.map(El => (
```
Comment (julien51) [inline unlock-app/src/components/interface/Header.js]: El is not a great name :(

File: unlock-app/src/components/interface/buttons/Button.js [hunk 2]
```diff
@@ -86,7 +86,7 @@ export const ButtonLink = styled.a`
 export const Label = styled.small`
   display: none;
   position: relative;
-  z-index: 1000;
+  z-index: 30000;
```
Comment (julien51) [inline unlock-app/src/components/interface/buttons/Button.js]: I think we need to use a couple variables for this because this is going to get complex very quickly.

**Comment by julien51** [comment]
Thanks!!

**Comment by cellog** [comment]
> Just checking - have you checked on mobile?

Yes, this doesn't affect anything on mobile, since the CSS grid is completely separate for that use case

File: unlock-app/src/components/interface/buttons/Button.js (hunk 2 above)
Comment (cellog) [reply unlock-app/src/components/interface/buttons/Button.js]: seems maybe a separate PR? Probably best to open an issue for this

File: unlock-app/src/components/interface/Header.js (hunk 1 above)
Comment (cellog) [reply unlock-app/src/components/interface/Header.js]: ok :) NavButton it is

**Comment by cellog** [comment]
#943 is for the z-index constants @julien51
