### PR TITLE
fix(subgraph): use `RoleChanged` event to parse lock managers

### LINKED ISSUE #10056: Subgraph handling NewLock event
When deploying locks thru ThirdWeb I realize the lock I deployed thru their UI is *not* showing up for me on the Unlock Dashboard.
I suspect it might be because we are not handling the event when they are _internal_?

Indeed, when deploying locks thru Thirdweb, the deployments are happening thru a 3rd party contract which calls the Unlock contract. [This is the transaction that deployed my lock](https://goerli.etherscan.io/tx/0x75a006d9e32df4efce45f3d135b146b5ffeb066c3cccc7af4461f685230bea37) and maybe that means we are not able identify the lock?

### PR DESCRIPTION
**Pull request by clemsos**
# Description

We use `RoleChanged` event to parse lock managers to prevent errors from the `NewRole` sending `msg.sender`.

# Issues

Fixes #10056
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: subgraph/src/public-lock.ts [hunk 1]
```diff
@@ -171,20 +172,28 @@ export function handleRenewKeyPurchase(event: RenewKeyPurchaseEvent): void {
...
-    lock.save()
-    log.debug('Lock manager {} added to {}', [
-      event.params.account.toHexString(),
-      event.address.toHexString(),
-    ])
+export function handleRoleGranted(event: RoleGrantedEvent): void {
+  // keccak 256 of 'LOCK_MANAGER'
+  if (
+    event.params.role.toString() ==
+    'B89CDD26CDDD51301940BF2715F765B626B8A5A9E2681AC62DC83CC2DB2530C0'
```
Comment (julien51) [inline subgraph/src/public-lock.ts:181]: Import from constants?

**Review by julien51 — COMMENTED** [review]
This looks pretty clean!

File: subgraph/src/public-lock.ts (hunk 1 above)
Comment (clemsos) [reply subgraph/src/public-lock.ts]: yep added to the main helpers
