### PR TITLE
fixing copy for SIWE. Fixes #10320

### LINKED ISSUE #10320: Copy misalignment on Sign In With Ethereum
**Describe the bug**
‘web3 wallet’ in the body should be ‘crypto wallet’ to align with the CTA copy. 

‘Getting Started’ in the body should be ‘Get started’ to align with the CTA copy. 

Is it Unlock account or Unlock Account?

### PR DESCRIPTION
**Pull request by julien51**
# Description

# Issues

Fixes #
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: unlock-app/src/components/interface/checkout/Connect/Confirm.tsx [hunk 1]
```diff
@@ -92,10 +92,10 @@ export function ConfirmConnect({
                   href="https://ethereum.org/en/wallets/"
                   rel="noreferrer"
                 >
-                  web3 wallet
+                  crypto wallet
                 </a>{' '}
-                if you have one, or click the &quot;Getting Started&quot; button
-                to use an Unlock account.
+                if you have one, or click the &quot;Get Started&quot; button to
+                use an Unlock account.
```
Comment (searchableguy) [inline unlock-app/src/components/interface/checkout/Connect/Confirm.tsx:98]: Account or account as per Patrick comment?

Just confirming.

**Review by searchableguy — APPROVED** [review]

File: unlock-app/src/components/interface/checkout/Connect/Confirm.tsx (hunk 1 above)
Comment (julien51) [reply unlock-app/src/components/interface/checkout/Connect/Confirm.tsx:98]: I don't think we need to capitalize
