### PR TITLE
Restore behavior of unlocked flag

### LINKED ISSUE #1477: The paywall flag immediately minimizes instead of delaying
**Describe the bug**
The paywall flag immediately minimizes, rather than sitting open for the delay from constants.js

### PR DESCRIPTION
**Pull request by cellog**
# Description

This returns the unlock flag to the original behavior of waiting 2 seconds before minimizing and fading.

out
# Issues

Fixes #1477 

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/paywall-builder/iframe.js [hunk 1]
```diff
@@ -35,12 +35,18 @@ export function hide(iframe, document) {
...
   document.body.style.overflow = ''
   iframe.style.backgroundColor = 'transparent'
   iframe.style.backgroundImage = 'none'
-  iframe.style['margin-right'] = collapsedMargin
+  iframe.style.marginRight = 0
+
+  setTimeout(() => {
+    open = false
+    iframe.style.marginRight = collapsedMargin
+  }, 2000)
```
Comment (julien51) [inline paywall/src/paywall-builder/iframe.js]: Quick nit: do you mind setting a constant for this? Maybe re-use SHOW_FLAG_FOR?

Comment (cellog) [reply paywall/src/paywall-builder/iframe.js]: sure

**Comment by cellog** [comment]
tooling is blocking this from passing
