### PR TITLE
Detect account changes

### LINKED ISSUE #1242: watch for account change to prevent 'invalid from address' error
**Describe the bug**
Switching web3 accounts after the lock has loaded causes an error in web3

**To Reproduce**
1. Visit https://www.ouvre-boite.com/members/ with an account that doesn't have a key 
2. Switch accounts in MetaMask
3. Click Purchase
4. See error in console: `MetaMask - RPC Error: Error: WalletMiddleware - Invalid "from" address.`

**Expected behavior**
Watch for changes and update the selected account

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome 
 - Version: 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask: v5.3.1

**Additional context**
FYI, I'm doing it like this atm but I'm not sure how well `publicConfigStore`    is supported...

```
    // watch changes to current account
    web3.currentProvider.publicConfigStore.on('update', data => {
      if (data.selectedAddress) {
        store.dispatch({
          type: 'ACCOUNT_CHANGE',
          payload: {
            currentAccount: data.selectedAddress
          }
        });
      } else {
        store.dispatch({
          type: 'ACCOUNT_LOGOUT'
        });
      }
    });
```

### PR DESCRIPTION
**Pull request by cellog**
# Description

This fixes #1242 

~~It depends on #1360 to be merged and will need a rebase (and replace of all references to `500` ms with the polling constant). Otherwise, it can be reviewed as is.~~

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

File: unlock-app/src/services/walletService.js [hunk 1]
```diff
@@ -26,15 +26,25 @@ export const keyId = (lock, owner) => [lock, owner].join('-')
  * actually retrieving the data from the chain/smart contracts
  */
 export default class WalletService extends EventEmitter {
-  constructor(availableProviders = providers) {
+  constructor(
+    availableProviders = providers,
+    timeout = setTimeout,
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: This is very very strange. I am not sure this is the right approach. Are jest time mocks working?

File: unlock-app/src/__tests__/services/walletService.test.js [hunk 2]
```diff
@@ -61,9 +61,56 @@ describe('WalletService', () => {
   beforeEach(() => {
     nock.cleanAll()
     providers = configure().providers
-    walletService = new WalletService(providers)
+    walletService = new WalletService(providers, () => {})
```
Comment (julien51) [inline unlock-app/src/__tests__/services/walletService.test.js]: I see you pass the second argument just to "mock" the setTimeout, right?
I really think this is not the right approach :/

File: unlock-app/src/services/walletService.js [hunk 3]
```diff
@@ -91,12 +102,22 @@ export default class WalletService extends EventEmitter {
...
+    if (isServer) return
+    this.account = await this.getAccount(true, this.account)
+    timeout(this.pollForAccountChange, POLLING_INTERVAL)
+  }
+
   /**
    * Function which yields the address of the account on the provider or creates a key pair.
    */
-  getAccount() {
+  getAccount(polling = false, priorAccount) {
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Hum, I think we should keep that function "clean" and put the logic of checking wether the account changed inside the `pollForAccountChange`? `getAccount` should just get the account while `pollForAccountChange` is actually the function which should know/care about whether the account changed.

File: unlock-app/src/services/walletService.js (hunk 1 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: no, jest time mocks do not work. at all.

**Comment by cellog** [comment]
note: the current changes depend on #1370 being merged and rebased. Currently, the PR does 2 things

**Comment by cellog** [comment]
ready for a 2nd pass, @julien51

File: unlock-app/src/middlewares/walletMiddleware.js [hunk 4]
```diff
@@ -31,7 +31,7 @@ export default function walletMiddleware({ getState, dispatch }) {
   // Buffer of actions waiting for connection
   const actions = []
 
-  const walletService = new WalletService()
+  const walletService = new WalletService(config.providers, config.isServer)
```
Comment (julien51) [inline unlock-app/src/middlewares/walletMiddleware.js]: Great!
I was actually thinking about your complaints that we inject the configuration everywhere and I was wondering if there was just a way to pass the *full* config object by default everywhere and then use named assignments in the constructor signatures... but that's for another PR!

File: unlock-app/src/services/walletService.js [hunk 5]
```diff
@@ -26,7 +28,7 @@ export const keyId = (lock, owner) => [lock, owner].join('-')
  * actually retrieving the data from the chain/smart contracts
  */
 export default class WalletService extends EventEmitter {
-  constructor(availableProviders = providers) {
+  constructor(availableProviders, runningOnServer, wait = delayPromise) {
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Still not a huge fan of the `wait` thing here, especially because I worry this will create weird problems when we add params to this function.
What do you think of passing a object like this:
```suggestion
  constructor({availableProviders: config.providers, runningOnServer: config.isServer, runningOnServer, wait:  delayPromise} = configure()) {
```

This lets us just call this with no object and would use the config by default, making "pure" function while still avoiding the hassle of drilling down the config all over?

File: unlock-app/src/services/walletService.js [hunk 6]
```diff
@@ -91,6 +94,35 @@ export default class WalletService extends EventEmitter {
...
+      try {
+        this.account = await this.checkForAccountChange(this.account)
+      } catch (e) {
+        continue // if the account poll fails, silently ignore it
+      }
+    }
+  }
+
+  async checkForAccountChange(priorAddress) {
+    const accounts = await this.web3.eth.getAccounts()
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: I think there is some logic duplicated here with `getAccount`. Any way to DRY this up?

Comment (julien51) [reply unlock-app/src/services/walletService.js]: [that probably means splitting up `getAccount` and/or `getOrCreateAccount` which is fine.

File: unlock-app/src/services/walletService.js [hunk 7]
```diff
@@ -91,6 +94,35 @@ export default class WalletService extends EventEmitter {
     }
   }
 
+  /**
+   * Poll to see if account has changed
+   */
+  async pollForAccountChange(timeout, isServer) {
+    if (isServer) return
+    while (true) {
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Not a huge fan of `while (true)`.

Couldn't we just call `pollForAccountChange` after we have waited for the stuff we care about?

Comment (cellog) [reply unlock-app/src/services/walletService.js]: Perhaps a little clever `await this.pollAccountChange()` at the end of the function? Although this will kill the call stack eventually. Hmm... Let think on this

File: unlock-app/src/services/walletService.js (hunk 5 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: Sure so perhaps a new PR to include the promise into the configuration? Then we extract it like this?

Comment (cellog) [reply unlock-app/src/services/walletService.js]: Sure so perhaps a new PR to include the promise into the configuration? Then we extract it like this?

File: unlock-app/src/middlewares/walletMiddleware.js (hunk 4 above)
Comment (cellog) [reply unlock-app/src/middlewares/walletMiddleware.js]: Yes this would be a great solution to that particular issue. Would you like that PR to be a follow-up or a precursor to this one?

Comment (cellog) [reply unlock-app/src/middlewares/walletMiddleware.js]: I'll do it as a precursor because why not :)

File: unlock-app/src/services/walletService.js (hunk 5 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: Something feels odd about including a promise-that-never-changes in configuration. Perhaps a 2nd parameter for utils so we get:

```js
constructor({availableProviders: config.providers, runningOnServer: config.isServer, runningOnServer}, { delayPromise }}) {
```

Also, I removed the default value of `configure()` from my example, primarily because we can easily do that inside `walletMiddleware`, which is currently the only place `walletService` is initialized in any case. What do you think?

File: unlock-app/src/services/walletService.js (hunk 6 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: sure I'll see what I can wrangle up

File: unlock-app/src/__tests__/services/walletService.test.js [hunk 8]
```diff
@@ -55,15 +57,75 @@ nock.emitter.on('no match', function(clientRequestObject, options, body) {
 })
 
 let walletService
+let config
 let providers
 
 describe('WalletService', () => {
+  const WalletService = require('../../services/walletService').default
```
Comment (julien51) [inline unlock-app/src/__tests__/services/walletService.test.js]: I think this really belongs in the top of the file?

File: unlock-app/src/services/walletService.js [hunk 9]
```diff
@@ -73,8 +75,10 @@ export default class WalletService extends EventEmitter {
     this.web3 = new Web3(provider)
 
     const networkId = await this.web3.eth.net.getId()
-    if (unlockAddress) {
-      this.unlockContractAddress = Web3Utils.toChecksumAddress(unlockAddress)
+    if (this.unlockAddress) {
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: I think it is strange that we have both `this.unlockAddress` and `this.unlockContractAddress`? I think we only use the latter one. Could we just maybe move this part to the constructor and not use `this.unlockAddress` anymore?

File: unlock-app/src/__tests__/services/walletService.test.js (hunk 8 above)
Comment (cellog) [reply unlock-app/src/__tests__/services/walletService.test.js]: The loading of promises.js has to happen after the `jest.mock('../../utils/promises')` so we can't use import, but have to use require. It's awkward but that's the price of module mocks :)

File: unlock-app/src/services/walletService.js [hunk 10]
```diff
@@ -25,15 +25,17 @@ export const keyId = (lock, owner) => [lock, owner].join('-')
  * actually retrieving the data from the chain/smart contracts
  */
 export default class WalletService extends EventEmitter {
-  constructor(availableProviders = providers) {
+  constructor({ providers, runningOnServer, unlockAddress } = configure()) {
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: 👍

File: unlock-app/src/services/walletService.js [hunk 11]
```diff
@@ -25,15 +25,17 @@ export const keyId = (lock, owner) => [lock, owner].join('-')
...
     super()
-    this.providers = availableProviders
+    this.unlockAddress = unlockAddress
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Move the `Web3Utils.toChecksumAddress` part from below up here so we do not have both `this.unlockAddress` and `this.unlockContractAddress`.

File: unlock-app/src/services/walletService.js [hunk 12]
```diff
@@ -91,23 +95,58 @@ export default class WalletService extends EventEmitter {
...
-      if (accounts.length === 0) {
-        return this._createAccount()
-      } else {
-        return Promise.resolve(accounts[0]) // defaults to the first account for now
-      }
-    })
+  async pollForAccountChange(isServer) {
+    if (isServer) return
+    try {
+      await delayPromise(POLLING_INTERVAL)
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Is there any reason why the `delayPromise` would throw? IIRC it does not based on what you sent earlier?

File: unlock-app/src/services/walletService.js [hunk 13]
```diff
@@ -91,23 +95,58 @@ export default class WalletService extends EventEmitter {
...
+    } catch (e) {
+      return // if the timeout throws, we don't start the loop, this is primarily for testing
+    }
+    try {
+      this.account = await this.checkForAccountChange(this.account)
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Same here, is there any reason it would throw?

File: unlock-app/src/services/walletService.js [hunk 14]
```diff
@@ -91,23 +95,58 @@ export default class WalletService extends EventEmitter {
...
+    } catch (e) {
+      // if the account poll fails, silently ignore it
+    }
+    // because this is async, the call stack is not affected, and does not grow
+    // for a non-async function this would quickly fill all available memory
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Great comment!

File: unlock-app/src/services/walletService.js [hunk 15]
```diff
@@ -91,23 +95,58 @@ export default class WalletService extends EventEmitter {
...
+    this.pollForAccountChange()
+  }
+
+  /**
+   * given the prior account address, determine if the account has changed and return the
+   * current address regardless of any change
+   */
+  async checkForAccountChange(priorAddress) {
+    const nextAddress = await this._getAccountAddress(Promise.resolve(null))
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: What is this promise passed as argument?

Comment (julien51) [reply unlock-app/src/services/walletService.js]: Maybe name the function in a way that makes it more obvious what the argument is? `_getAccountAddressOrFallback`  for example ;)

File: unlock-app/src/services/walletService.js [hunk 16]
```diff
@@ -91,23 +95,58 @@ export default class WalletService extends EventEmitter {
...
-    })
+    const address = await this._getAccountAddress(this._createAccount)
+    this.emit('account.changed', address)
+    this.emit('ready')
+    return Promise.resolve(address)
+  }
+
+  /**
+   * Get the current user account address, calling a fallback if there is none
+   * @param fallback async function
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Make it clear that the fallback should also return/yield an address.

File: unlock-app/src/utils/__mocks__/promises.js [hunk 17]
```diff
@@ -0,0 +1,17 @@
+let x = 0
```
Comment (julien51) [inline unlock-app/src/utils/__mocks__/promises.js]: What's the `x`? Maybe use a better variable name?

File: unlock-app/src/utils/__mocks__/promises.js [hunk 18]
```diff
@@ -0,0 +1,17 @@
...
+
+const delayPromise = jest.fn(ms => {
+  if (x--) {
```
Comment (julien51) [inline unlock-app/src/utils/__mocks__/promises.js]: This is not pure ;p
Not sure what `delayPromise` does actually?

Comment (cellog) [reply unlock-app/src/utils/__mocks__/promises.js]: first of all, my main takeaway from your feedback is that the PR is not clear enough from a devel perspective, and this needs fixin!

To answer this specific point, the main issue that makes this PR so dang hard to do well is that the account is polled every half second.

The simplest solution is to use a `setInterval` but it turns out that this can wreak havoc on mobile browsers, according to the coinbase doc that Akeem and I used as a cheat sheet on our beginning exploration of this problem.

The next-most-simplest solution (setTimeout and infinitely looping) caused the tests to flail about like a fish and slowly croak when I tried to mock it with `jest.useFakeTimers()`. So, I moved to the delay promise, because it allows us to mock it out without using fake timers. A few commits ago, when it was passed as a parameter to the `walletService`, I could then directly pass in what this mock does, which is provide a delay promise that neither delays, nor loops.

In other words, I need a promise that will only successfully resolve once, and then reject. The rejection is the thing that kicks the account polling out of its infinite looping.

This mock module allows us also to specify the number of times that our delay will be called, in case we want to use it in the future and need more calls to succeed. Note that by default, the delay promise never resolves, and only rejects. This allows us to not generate an infinite loop in the other `walletService` tests, which prevents all kinds of weird side effects in those tests, mostly failing because the test doesn't mock a call to `web3.eth.getAccounts()`.

If this sounds incredibly complex, it's because it is. It took me 10 minutes to write the first working version of this, and has taken about 5 hours of work and 4+ days to get to this stage :). I'm not complaining, it's been a fun challenge, but it's a doozy, and I'm not surprised my code is not easy to read as a result.

Maybe we can chat briefly and look over the PR together for 10 minutes tomorrow, finalize how to solve/name/comment things and then I can implement any changes?

File: unlock-app/src/__tests__/services/walletService.test.js (hunk 8 above)
Comment (julien51) [reply unlock-app/src/__tests__/services/walletService.test.js]: What? let's debug this tomorrow because I have been using mocks all over the place and never had to do that ;)
jest will actually hoist the mock for modules at the beginning of files no matter what.

**Comment by cellog** [comment]
OK, @julien51 PTAL, I think this is going to be much better

File: unlock-app/src/services/walletService.js (hunk 13 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: yes, if web3 throws.

Comment (cellog) [reply unlock-app/src/services/walletService.js]: (which it does inside an iframe in coinbase wallet, getAccount() freaks out)

File: unlock-app/src/__tests__/services/walletService.test.js [hunk 19]
```diff
@@ -55,15 +58,64 @@ nock.emitter.on('no match', function(clientRequestObject, options, body) {
 })
 
 let walletService
+let config
 let providers
 
 describe('WalletService', () => {
+  let delay
   beforeEach(() => {
+    delay = require('../../utils/promises').delayPromise
```
Comment (julien51) [inline unlock-app/src/__tests__/services/walletService.test.js]: I still don't like with that ;)

File: unlock-app/src/services/walletService.js (hunk 13 above)
Comment (julien51) [reply unlock-app/src/services/walletService.js]: Is there a way to only catch that error? I m not a huge fan of blanket `catch (e)` which catches and swallows everything.

File: unlock-app/src/services/walletService.js [hunk 20]
```diff
@@ -91,23 +98,64 @@ export default class WalletService extends EventEmitter {
...
+      this.emit('account.changed', nextAccount)
+    }
+    return nextAccount
+  }
+
+  /**
+   * Function which yields the address of the account on the provider or creates a key pair.
+   */
+  async getAccount() {
     // Once we have the account, let's refresh it!
```
Comment (julien51) [inline unlock-app/src/services/walletService.js]: Remove this?

File: unlock-app/src/__tests__/services/walletService.test.js (hunk 19 above)
Comment (cellog) [reply unlock-app/src/__tests__/services/walletService.test.js]: The mock for delayPromise is a `jest.fn()` so we need a new one for every test. That's all this does, is give us something to assert on. Is that kosher? :)

File: unlock-app/src/services/walletService.js (hunk 20 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: remove what?

File: unlock-app/src/__tests__/services/walletService.test.js (hunk 19 above)
Comment (cellog) [reply unlock-app/src/__tests__/services/walletService.test.js]: This allows the tests to assert on the mock surrounding the promise function. Because we don't pass it as a parameter to the service, this is the only way to get a new one for every test.

File: unlock-app/src/services/walletService.js (hunk 13 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: I'm pretty sure it's a generic Error, so I don't think so. Also, there may be new errors introduced later. The solution is a TODO that says "log error here" for when we implement Akeem's idea of logging

File: unlock-app/src/services/walletService.js (hunk 20 above)
Comment (cellog) [reply unlock-app/src/services/walletService.js]: sorry, remove what?

File: unlock-app/src/__tests__/services/walletService.test.js [hunk 21]
```diff
@@ -16,6 +15,11 @@ import {
   FAILED_TO_UPDATE_KEY_PRICE,
   FAILED_TO_WITHDRAW_FROM_LOCK,
 } from '../../errors'
+import { POLLING_INTERVAL } from '../../constants'
+
+jest.mock('../../utils/promises')
+const WalletService = require('../../services/walletService').default
```
Comment (julien51) [inline unlock-app/src/__tests__/services/walletService.test.js]: Huuuhuhuh I wish you'd use a regular import here. Please fix this or add a comment about why you need to use `require` here? This is going to be extremely confusing in 2 weeks.

File: unlock-app/src/__tests__/services/walletService.test.js [hunk 22]
```diff
@@ -16,6 +15,11 @@ import {
...
+const delay = require('../../utils/promises').delayPromise
```
Comment (julien51) [inline unlock-app/src/__tests__/services/walletService.test.js]: Same here?
