### PR TITLE
fix(unlock-app): Show scan-another button always + add close button to membership card on verification page

### LINKED ISSUE #9258: Show "scan next" in every case? (add a "close")
We should let the user "scan the next ticket" in all cases, whether the user is a verifier or not, and/or whether the current ticket was checked-in or not.

### PR DESCRIPTION
**Pull request by searchableguy**
# Description

Adds close button card and make scan-another persistent + show check in button only to verifier. 

# Issues

Fixes #9258
Refs #

# Checklist:

- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: unlock-app/src/components/interface/verification/Scanner.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import {
 } from '~/utils/verification'
 import VerificationStatus from '../VerificationStatus'
 import QrScanner from 'qr-scanner'
+import { FaWindowClose as CloseIcon } from 'react-icons/fa'
```
Comment (julien51) [inline unlock-app/src/components/interface/verification/Scanner.tsx:9]:
```suggestion
```

**Review by julien51 — APPROVED** [review]
