### PR TITLE
fully fix optimistic unlocking in coinbase wallet-like browsers

### LINKED ISSUE #2351: Paywall cannot do optimistic unlocking when opened in a new window
When the paywall opens in a new window, such as in a coinbase wallet purchase, we cannot properly handle optimistic unlocking. The reason is that if we do the optimistic unlock in the new window, there is no content to view. If we redirect back to the old window, then we don't have access to the transaction any longer, and the content is simply displayed as purchased.

This will require larger changes to the app, specifically enabling the same kind of ability to retrieve the transaction for a key purchase that is used on the creator dashboard to retrieve the transaction for lock creation.

### PR DESCRIPTION
**Pull request by cellog**
# Description

This is the final piece of logic in the quest to enable optimistic unlocking in coinbase wallet-like browsers. It redirects to the main window when the transaction becomes pending, and keeps the paywall locked until the transaction is confirmed.

This also means that the paywall will work even on refresh!

# Issues

Fixes #2351 

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/components/Paywall.js [hunk 1]
```diff
@@ -142,7 +144,22 @@ export const mapStateToProps = ({
...
+  }
+  if (!locked && !validKeys.length) {
+    locked = true
+  }
+  if (!locked && transaction) {
+    if (
+      !transaction.confirmations ||
+      transaction.confirmations < requiredConfirmations
+    ) {
+      locked = true
```
Comment (julien51) [inline paywall/src/components/Paywall.js]: Good one!
