### PR TITLE
prefix all redux actions

### LINKED ISSUE #1052: redux action types can collide
**Describe the bug**
Currently, redux action constants are co-located with the actions. Although this provides a convenience, it is dangerous.

For instance, I just tried to define a constant named UPDATE_LOCK, which already exists.

There is nothing that would have caught this, except that upon dispatching the actions, it would trigger in 2 different reducers with unpredictable results

There are 2 possible solutions

1) prefix each action type with its filename:

```js
const UPDATE_LOCK = 'locks/UPDATE_LOCK'
```

Because we use constants, there is no usability issue

2) move all constants to a single "types.js" file

This is a lot more work initially, but is a possible solution

Because I just ran into this issue, it is something that will come up again, and when it happens it may not be obvious for a while depending on how similar the actions are.

### PR DESCRIPTION
**Pull request by cellog**
# Description

Fixes #1052 by adding a prefix based on the file name to every redux action constant, and fixing the few locations where constants were not being used.

screen shot 2019-01-23 at 11 03 46 pm

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

PS: [Read how to write the perfect pull request](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

### CODE REVIEW

File: unlock-app/src/actions/currencyconvert.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
-export const SET_ETHER_CONVERSION_RATE = 'SET_ETHER_CONVERSION_RATE'
+export const SET_ETHER_CONVERSION_RATE =
+  'currencyconvert/SET_ETHER_CONVERSION_RATE'
```
Comment (julien51) [inline unlock-app/src/actions/currencyconvert.js]: Damned. I wish I did not miss the case issue on that one :(
