### PR TITLE
Pass the correct flag to checkoutHandlerInit [fixes master regression]

### LINKED ISSUE #5378: Injected balance is wrong for managed key purchases
**Describe the bug**
Pasted from #5377:
> image

> This is on the Ouvre-Boite staging page with no metamask (i.e., trying to use a managed account). The Eth lock should be disabled, and the WEE lock should be active. I think there's something wrong somehow in the injected balance.

This issue is only in staging at the moment, prod is unaffected. I believe this is related to the paywall refactoring.

**To Reproduce**
1. On staging, go to a page that supports user accounts
2. Launch the checkout modal
3. Note that ERC20 locks show as having insufficient balance and ETH locks show as having correct balance

**Expected behavior**
ERC20 locks should have an injected balance that allows a user to do a managed key purchase with them. ETH locks should be disabled.

### PR DESCRIPTION
**Pull request by cnasc**
# Description

In the course of refactoring the paywall, I forgot to remove the Wallet-local variable used to determine whether we used user accounts. It defaulted to false, and was never updated. Therefore, when it was passed to the checkout handler init, it would never allow the default balance injection to occur, which led to the issue we discovered yesterday.

This PR cleans that up. _We should do a manual production push after this is merged_

# Issues

Fixes #5378 

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [x] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [x] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [x] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/unlock.js/CheckoutUIHandler.ts [hunk 1]
```diff
@@ -56,7 +56,6 @@ export default class CheckoutUIHandler {
       config: this.config,
       dataIframe: this.iframes.data,
       checkoutIframe: this.iframes.checkout,
-      injectDefaultBalance,
```
Comment (cnasc) [inline paywall/src/unlock.js/CheckoutUIHandler.ts]: In this case I removed the class-local version of injectDefaultBalance from being used in the init, now that we've extracted it to a util. A next step will be to delete the code duplication.

File: paywall/src/unlock.js/Wallet.ts [hunk 2]
```diff
@@ -27,7 +27,6 @@ export default class Wallet {
   private readonly window: Web3Window
   private readonly config: PaywallConfig
   private hasWeb3: boolean = false
-  useUserAccounts: boolean = false
```
Comment (cnasc) [inline paywall/src/unlock.js/Wallet.ts]: That was the unused variable at the root cause of this issue.

**Comment by julien51** [comment]
Let's schedule a push on Monday, this should be 4 days in?
