### PR TITLE
fix(unlock-app): changing withdraw amount input from range to number.

### LINKED ISSUE #11944: "fixed" amount withdraws
Our withdraw UI lets the user chose what amount they want to withdraw with a bar.
We also need to let the user enter a fixed amount. That amount needs to bet between `0` and the full balance, rather than only decimal amounts.

For example on the screen below I want to withdraw 20 USDC exactly but I cannot.

Screenshot 2023-05-19 at 2 29 41 PM

### PR DESCRIPTION
**Pull request by julien51**
# Description

This fixes #11944 and #12331
Screenshot 2023-08-04 at 10 52 16 AM

# Issues

Fixes #
Refs #

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [X] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx [hunk 1]
```diff
@@ -220,18 +220,18 @@ export const WithdrawFundModal = ({
               />
 
               <Input
-                label={`Balance to transfer: ${amountToTransfer} ${symbol}`}
+                label={`Balance to transfer: ${amountToTransfer} of ${balance} ${symbol}`}
                 size="small"
-                type="range"
+                type="number"
```
Comment (searchableguy) [inline unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx:225]: Change this to text and add a number pattern to input.

Set valueAsNumber to true in register options.

**Review by searchableguy — APPROVED** [review]

File: unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx (hunk 1 above)
Comment (julien51) [reply unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx:225]: Please explain so I learn why!

Comment (julien51) [reply unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx:225]: Will replace across the board in another PR!
