### PR TITLE
does not create a temporary key on failed transactions

### LINKED ISSUE #4858: Failed transactions should not yield optimitic keys
When purchasing a key, if the transaction failed, we should not yield optimistic keys.

### PR DESCRIPTION
**Pull request by julien51**
# Description

While doing some tests with @cnasc, we found that failed transactions would still benefit from our optimistic unlocking.
This PR changes that: failed transaction should not be considered optimistic!

# Issues

Fixes #4858

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts [hunk 1]
```diff
@@ -331,7 +331,7 @@ export default class BlockchainHandler {
       {
         hash,
         blockNumber: Number.MAX_SAFE_INTEGER,
-        status: 'submitted',
+        status: TransactionStatus.SUBMITTED,
```
Comment (cnasc) [inline paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts]: Thanks for updating this!
