### PR TITLE
do not retrieve key without a valid account address.

### LINKED ISSUE #1362: web3Middleware should not try to retrieve when no the redux store does not have an account
**Describe the bug**
When loading the paywall with no account, it fails with an exception in `web3Middleware`

The lines in question are:

```js
      if (action.type === ADD_LOCK || action.type == UPDATE_LOCK) {
        const lock = getState().locks[action.address]
        web3Service.getKeyByLockForOwner(
          lock.address,
          getState().account.address
        )
```

When pausing on the `getKeyByLockForOwner` when logged in, the lock has an address. When pausing while logged out, the lock has no address, and does not exist in state, so `lock` is undefined. In addition, a casual look shows that we are assuming that the `account` in state has an address, where it is in fact `null` when there is no account.

**To Reproduce**
1. run `UNLOCK_ENV=staging npm run dev`
2. go to `http://localhost:3000/paywall/0x42dbdc4CdBda8dc99c82D66d97B264386E41c0E9`
3. See error

**Expected behavior**
lock displays under a "missing wallet" error

**Screenshots**
screen shot 2019-02-01 at 9 28 23 pm

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome with Metamask logged out

### PR DESCRIPTION
**Pull request by julien51**
fixes #1362

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: unlock-app/src/middlewares/web3Middleware.js [hunk 1]
```diff
@@ -123,10 +123,12 @@ export default function web3Middleware({ getState, dispatch }) {
 
       if (action.type === ADD_LOCK || action.type == UPDATE_LOCK) {
         const lock = getState().locks[action.address]
-        web3Service.getKeyByLockForOwner(
-          lock.address,
-          getState().account.address
-        )
+        if (getState().account) {
```
Comment (cellog) [inline unlock-app/src/middlewares/web3Middleware.js]: can probably move this up 1 line, since lock is unused otherwise
