### PR TITLE
fix key purchase on coinbase wallet

### LINKED ISSUE #2129: Coinbase Wallet does not open new window when tapping on a lock to purchase
Open up any locked page, and tap on the lock in coinbase wallet, and it will not redirect to a new page. It appears that the postMessage to the main window is not happening.

### PR DESCRIPTION
**Pull request by cellog**
# Description

This PR fixes a final piece of the puzzle missed in the refactor of the paywall to use hooks. Redirecting to a new window uses postMessage, but the `Lock` component did not use this. Because the old system did not pass the origin in messages, which was insecure, the `interWindowCommunicationMiddleware` call to `window.parent.postMessage` was being discarded by the paywall.

This PR fixes that issue by using the new (far more secure) `usePostMessage` hook, which pulls the parent window's origin from the URL and uses that to call `postMessage` properly.

This PR also introduces new testing for the Lock using `react-testing-library` which will make it far less fragile when making future changes, and much more likely to catch regressions.

# Issues

Fixes #2129 

# Checklist:

- [X] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes (package.json, etc.)
  - [X] This PR only contains code changes (if configuration changes are required, do a separate PR first, then re-base)
- [X] My code follows the style guidelines of this project, including naming conventions
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] If my code adds or changes components, I have written corresponding stories with Storybook
- [X] I have performed a self-review of my own code
- [ ] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: paywall/src/components/lock/Lock.js [hunk 1]
```diff
@@ -22,7 +23,15 @@ export const Lock = ({
   config,
   disabled,
   hideModal,
+  openInNewWindow,
 }) => {
+  const { postMessage } = usePostMessage()
+  const purchase = key => {
```
Comment (julien51) [inline paywall/src/components/lock/Lock.js]: Wouldn't it make more sense to put that logic inside `mapStateToProps`? This would at least make it testable much more easily?

Comment (cellog) [reply paywall/src/components/lock/Lock.js]: Hooks cannot be outside of components. I could make a new custom hook if you'd like?

**Comment by cellog** [comment]
refactored, PTAL

File: paywall/src/__tests__/components/lock/Lock.test.js [hunk 2]
```diff
@@ -103,4 +94,57 @@ describe('Lock', () => {
       expect(newProps.transaction).toEqual(state.transactions['0x777'])
     })
   })
+  describe('usePurchaseKey is called for purchases', () => {
```
Comment (julien51) [inline paywall/src/__tests__/components/lock/Lock.test.js]: nit: space above

File: paywall/src/components/lock/Lock.js [hunk 3]
```diff
@@ -68,6 +70,7 @@ Lock.propTypes = {
   purchaseKey: PropTypes.func.isRequired,
   config: UnlockPropTypes.configuration.isRequired,
   hideModal: PropTypes.func.isRequired,
+  showModal: PropTypes.func.isRequired,
```
Comment (julien51) [inline paywall/src/components/lock/Lock.js]: weird. Was it missing before? It looks like your changes do not use it?

File: paywall/src/hooks/usePurchaseKey.js [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+  const purchase = useCallback(
+    key => {
+      if (openInNewWindow) {
+        return postMessage(POST_MESSAGE_REDIRECT)
+      }
+      purchaseKey(key)
+    },
+    [purchaseKey, postMessage, openInNewWindow]
+  )
+  return purchase
```
Comment (julien51) [inline paywall/src/hooks/usePurchaseKey.js]: nit: move the `return` statement to `const purchase`?

File: paywall/src/stories/lock/Lock.stories.js [hunk 5]
```diff
@@ -5,11 +5,22 @@ import { Lock } from '../../components/lock/Lock'
 import createUnlockStore from '../../createUnlockStore'
 import { ConfigContext } from '../../utils/withConfig'
 import { UNLIMITED_KEYS_COUNT } from '../../constants'
+import { WindowContext } from '../../hooks/browser/useWindow'
```
Comment (julien51) [inline paywall/src/stories/lock/Lock.stories.js]: I am confused by the choice of variable name. It looks like most (all?) hooks use `useXX`. why here a name which looks like a component?

Comment (julien51) [reply paywall/src/stories/lock/Lock.stories.js]: But that is probably for another PR: maybe add a `TODO rename` comment so we can keep track of this?

File: paywall/src/__tests__/hooks/usePurchaseKey.test.js [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+      const component = rtl.render(<MockPurchaseKey />)
+
+      rtl.act(() => {
+        rtl.fireEvent.click(component.getByText('Click'))
+      })
+
+      expect(purchaseKey).toHaveBeenCalledWith('hi')
+      expect(postMessage).not.toHaveBeenCalled()
+    })
+    it('calls postMessage if openInNewWindow is true', () => {
```
Comment (julien51) [inline paywall/src/__tests__/hooks/usePurchaseKey.test.js]: nit: space above?

File: paywall/src/__tests__/hooks/usePurchaseKey.test.js [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+  })
+  function MockPurchaseKey() {
+    const purchase = usePurchaseKey(purchaseKey, openInNewWindow)
+    return (
+      <button type="button" onClick={() => purchase('hi')}>
+        Click
+      </button>
+    )
+  }
+  describe('purchase', () => {
```
Comment (julien51) [inline paywall/src/__tests__/hooks/usePurchaseKey.test.js]: nit: space above?

File: paywall/src/stories/lock/Lock.stories.js (hunk 5 above)
Comment (cellog) [reply paywall/src/stories/lock/Lock.stories.js]: this is the context, defined with `React.createContext` that is used to pass the `window` down. `useWindow.js` exports both this and the hook `useWindow`.

File: paywall/src/components/lock/Lock.js (hunk 3 above)
Comment (cellog) [reply paywall/src/components/lock/Lock.js]: it was in fact missing. This is not part of the limited scope of this PR, want me to move it to a separate PR?
